local icons = {}

icons.layout = {
  list = "•",
  tab = "→",
  wrap = "↪",
}

icons.widget = {
  active = "",
  branch = "",
  command = "",
  config = "",
  error = "",
  event = "",
  filetype = "",
  import = "",
  inactive = "",
  keymap = "",
  lazy = "",
  nesting = "",
  plugin = "",
  progress = "",
  ready = "",
  remote = "",
  runtime = "",
  source = "",
  start = "",
  task = "",
  telescope = " ",
  warning = "",
}

icons.kind = {
  Array = "",
  Boolean = "",
  Class = "",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  Function = "",
  Interface = "",
  Key = "",
  Keyword = "",
  Method = "",
  Module = "",
  Namespace = "",
  Null = "",
  Number = "",
  Object = "",
  Operator = "",
  Package = "",
  Property = "",
  Reference = "",
  Snippet = "",
  String = "",
  Struct = "",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
}

return icons
